### ISSUE TITLE
write_abacus_shell_model.py generates a mesh that can't be read by meshio

### ISSUE THREAD

**Issue by James-Ilosta** [sandialabs/pyNuMAD#16]
In the write_abacus_shell_model.py, it the script writes an inp file with additional commas after each node coordinate line:

i = 1
for nd in bladeMesh['nodes']:
    lst = [str(i),str(nd[0]),str(nd[1]),str(nd[2]), '\n']
    ln = ','.join(lst) + '\n'
    outFile.write(ln)
    i = i + 1

Producing:

1,-2.114282115869634,0.769617524822445,0.0,
2,-2.1373045369417625,0.7019296545882159,0.0,

The problem is that when meshio reads this, it treats this as an additional character at the end of the line: "" and then when it reads this it considers this empty character as an additional coordinate point and then returns an error as it can't convert the string "" to a float.

This is the case for the elements, adhesive nodes and adhesive elements.

I believe this can be resolved using the following lines:

i = 1
for nd in bladeMesh['nodes']:
    lst = [str(i),str(nd[0]),str(nd[1]),str(nd[2])]
    ln = ','.join(lst) + '\n'
    outFile.write(ln)
    i = i + 1

with similar changes for the other parameters I mentioned.

I don't think that this has an impact on how Abaqus would interact with these files, however any additional input on this would be appreciated

**Comment by andersone35** [comment]
Hi James, good to hear from you again.

That's right, the solution you showed should take away those commas at the end, and perhaps fix your problem.  That said, I am not familiar with meshio so I can't guarantee there wouldn't be more issues.  That output was meant for Abaqus, which has no problem with the extra commas.

If I'm not mistaken, that example also writes the mesh out in .yaml format, which may or may not help you in your situation.  But it is also there for your reference.

Thanks for the input, I may consider making the changes you suggest to the main repo to avoid this problem in the future.  Reach out if you need anything further.

Best,
Evan

**Comment by James-Ilosta** [comment]
Hi Evan,

Thanks for the reply. Good to hear from you too. Yes, I spoke with my colleague and it the comma at the end seems common for Abaqus inp files. At the moment, I'm looking for a fast way to output a mesh for visualisation. I was looking into using meshio and pyvista or vtk. I know there is/was a gui for matlab and so was giving this a go. I've also just seen the plotShellMesh tool too, although I find the viewer a little difficult to use. I'm not sure if you have a preferred way of doing this or whether this was typically Abaqus?

**Comment by andersone35** [comment]
Yeah I think Abaqus CAE makes a great viewer for things like this, but it's not available to everyone I know.  Have you considered tecplot, (www.tecplot.com)?  I believe that's free license and it's quite advanced for viewing, if you can just get the mesh into their format.
