### ISSUE TITLE
blade=pynumad.Blade()  AttributeError: module 'pynumad' has no attribute 'Blade'

### ISSUE THREAD

**Issue by mcMunich** [sandialabs/pyNuMAD#33]
I am trying to get started with the ansys_example.py

If I try to run the line pynumad.Blade() I get the: AttributeError: module 'pynumad' has no attribute 'Blade'

dir(pynumad) returns: 
['__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__']

I have a virtual environment
I pip install pynumad to that venv
I activate the venv.
I start python 
```
import pynumad
pynumad.Blade()
```

![image](https://github.com/sandialabs/pyNuMAD/assets/84008975/d4ba4826-360c-4d18-8fd7-ccd74a849255)

Windows 11, trying both from the cmd prompt and Spyder, python3.11

Any ideas if I am missing something (the lack of () was not the issue)

![image](https://github.com/sandialabs/pyNuMAD/assets/84008975/9979e8bd-25d0-447f-a6b3-e2df679d4188)

**Comment by kbonney** [comment]
Only noticed this issue today @mcMunich. Sounds like you were able to address the problem. If it isn't much trouble, mentioning how it got resolved in this thread might help future users.

**Comment by mcMunich** [comment]
I would like to help. In my case, there were multiple pynumad installations and either the wrong one or a wrong link was causing the issue. I had to clean up my directories (that is what the virtual env should help with) to get over this issue.

**Comment by kbonney** [comment]
Thanks for the update. Virtual environments are definitely the way to go. We should add some recommendations in our installation docs so that others know to use them.
